### ISSUE TITLE
Suggestion: about the about page of menu bar

### ISSUE THREAD

**Issue by XiaoXin1900** [SunnieShine/Sudoku#167]
1. I noticed that there is no version information of software in the software.  So I wonder if we can add a button in the about page to show software information(even not just version information).

2. It's a puzzle software. So I think maybe we can add a button to link to a Web Page, like Sudoku's Tutorial. a wiki?

🥰🥰

**Comment by SunnieShine** [comment]
Okay. I'll try it later. :D

**Comment by SunnieShine** [comment]
Okay. Finally.
