### ISSUE TITLE
A small Bug? : the number of times of trying to generate a puzzle maybe wrong

### ISSUE THREAD

**Issue by XiaoXin1900** [SunnieShine/Sudoku#168]
**Version 0.6**

When I generate a puzzle, hmmm, look the form's image below:
![form](https://user-images.githubusercontent.com/68503296/131160193-cdb163fd-73ae-464a-a662-bef0f4860600.png)
sometimes, the number of trying time will change form 1 to 0 and after that change back instantly, and maybe occur not only once. By the way, I never saw other numbers...

**Comment by SunnieShine** [comment]
@XiaoXin1900 
What mode you chose to generate the puzzle?

**Comment by SunnieShine** [comment]
This issue may occur at `Sudoku.Windows`, but this project is deprecated.
