### ISSUE TITLE
[Feature Request] A better experience to practice sudoku techniques

### ISSUE THREAD

**Issue by shincyan1900** [SunnieShine/Sudoku#170]
I guess if there is a function like this could be very interesting: After I generated a puzzle with special techniques, the consequence will be a puzzle that only the whole area that need special techniques to solve is empty, others is solved.

**Comment by SunnieShine** [comment]
I'll re-implement on MAUI. This function will be considered in that version.

**Comment by SunnieShine** [comment]
I'll re-implement on MAUI. This function will be considered in that version.
