### ISSUE TITLE
功能需求 请问能否增加一个功能判断填入的数是对是错

### ISSUE THREAD

**Issue by relic-yuexi** [SunnieShine/Sudoku#195]
![image](https://user-images.githubusercontent.com/53668275/152339937-76db3722-5395-431d-8693-b9e0c128c071.png)
像HoDoKu里如果填的是错的，就用红色标记。

---

## 作者添加内容

待完成列表：

- [x] 数据结构变更
- [x] 盘面在尚未验证之前，判断行列宫的数字是否冲突。
  - [x] 对于多解或无解题，仍需要对此进行验证。（程序设计说明：如果 a 和 b 同行列宫且同一个填数，那么由于 a 和 b 无法区分到底谁对谁错，所以程序会对两边数字**全部都**报错；除非其中一方是提示数，因为它无法修改，所以这个数字这种情况下不会报错）
  - [x] 对于唯一解题，需要对此进行验证。
- [x] 盘面需要进行唯一性和对解的验证，判断当前格子的填数是否是这个题目真的应该填入进去的数字。
  - [x] 对于无解或多解题，无需验证此内容，因为无法验证。
  - [x] 对于唯一解题，需要对此进行验证。
    - [x] 基本错误填数
    - [x] 错误删数
- [x] Bug 修复

**Comment by relic-yuexi** [comment]
感觉实现逻辑是，已知最后局面了，填入一个数的时候就与最后局面判断下，如果不一样就标红。

**Comment by SunnieShine** [comment]
行。

这个可以做的，不过最近我都在调 API 所以很久没有更 UI 了。我到时候做 UI 的时候我会做的。

**Comment by SunnieShine** [comment]
待完成列表：

- [ ] 盘面在尚未验证之前，判断行列宫的数字是否冲突。
- [ ] 盘面需要进行唯一性和对解的验证，判断当前格子的填数是否是这个题目真的应该填入进去的数字。
  - [ ] 对于无解题的情况
  - [ ] 对于多解题的情况
  - [ ] 对于唯一解题的情况

**Comment by SunnieShine** [comment]
你好。你的 issue 已经完成。感谢支持！
