### ISSUE TITLE
[Featuer Request] Support directly input dot or zero to skip blank cells in UI (界面上输入数字的时候支持点或者0表示空格)

### ISSUE THREAD

**Issue by prime167** [SunnieShine/Sudoku#713]
现在界面上的盘面输入不太方便，不支持0也不支持方向键
我现在输入盘面的时候都是先打开记事本，输入盘面000089....9400 再复制粘贴到界面上。可否添加直接在界面之用键盘输入盘面的功能？

**Comment by SunnieShine** [comment]
设计如此。

请使用鼠标移动到指定单元格，并按键盘进行输入。软件使用的是 JSudoku 的输入模式。

以后也不考虑更改此输入模式。
